### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [Nagaoka-22/mimic-quiz#38]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
・実際にルームに入って回答できるところまで確認できました。
・LGTMです。

## 静的コードチェックが入っている
・インデントが崩れている箇所がありましたので修正しましょう（Rubyは半角スペース2個）。
・使っていないコードでコメントアウトしている箇所は削除しておきましょう。
・Rubocopを通しましょう。

## 就活において十分な技術力を示せる機能を実装しているか
・リアルタイム通信を使ってのゲームが実装できていると感じました。十分に技術力は示せているかと思います。
・ルームIDのところはUUIDとかに変更しておきましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・1人の場合での動作確認が難しいため（就活ではおそらく1人の人がサービスを触るかと思われます）、ゲストログインでも操作の確認ができる工夫を用意しておくと良いかと思います。
・大きく問題がありそうな箇所はありませんでした。ただルームを検索する画面を開くとヘッダーが下部に固定できていなかったりと気になる箇所は修正しておきましょう。
・このサービスだけでゲームを楽しむイメージが付きにくかったです。Discordなどの補助があればワイワイできそうかとも思いましたが、ルーム内にチャット（「始めます！」「よろしく」などのテキストコニュミケーションができる場）があるとより良いように感じました。

■チャット
概要：FacebookメッセンジャーやSNSなどには、チャット機能が必ずついています。現在では、WebSocketを用いることで、リアルタイムでやり取りが可能となっています。コツさえ掴めば、比較的簡単に実装できます。ダイレクトメッセージのようなチャット機能を実装することで、ユーザー同士のコミュニケーションを活性化させることができるかもしれません。
使用技術・ライブラリ：
- WebSocket
  - https://ja.wikipedia.org/wiki/WebSocket
- ActionCable（Rails標準）
  - https://railsguides.jp/action_cable_overview.html

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by Nagaoka-22** [comment]
レビューありがとうございます！
いただいた内容をもとにissueを記載しました。
本リリースは9/18を予定しています。

**Comment by Tsuchiya2** [comment]
回答ありがとうございます。
引き続き開発頑張ってください。

== 追記 ==
独自ドメイン、サービスにアクセスした際にすぐにページが表示されるようにしましょう。
